# https://github.com/lowlighter/metrics/blob/master/source/plugins/anilist/README.md
name: Anilist Anime
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  fetch_anilist:
      runs-on: ubuntu-latest
      steps:
        - name: Update anime list
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.anilist.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_anilist_user: zukashishifu
            plugin_anilist: yes
            plugin_anilist_medias: anime
            plugin_anilist_sections: watching
            plugin_anilist_limit: 5
#             plugin_anilist_limit_characters: 20
