# https://github.com/lowlighter/metrics/blob/master/source/plugins/anilist/README.md
name: Anilist Char
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  fetch_waifus:
      runs-on: ubuntu-latest
      steps:
        - name: Favorite Characters
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.anilist.characters.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_anilist_user: zukashishifu
            plugin_anilist: yes
            plugin_anilist_sections: characters
            plugin_anilist_limit_characters: 22
