# https://github.com/lowlighter/metrics/blob/master/source/plugins/anilist/README.md
name: Anilist Manga
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  fetch_manga_list:
      runs-on: ubuntu-latest
      steps:
        - name: Favorites anime and currently watching
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.anilist.manga.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_anilist_user: zukashishifu
            plugin_anilist: yes
            plugin_anilist_medias: manga
            plugin_anilist_sections: favorites
            plugin_anilist_limit: 5
#             plugin_anilist_limit_characters: 20
