# src: https://github.com/marketplace/actions/anilist-readme-workflow
name: AniList readme workflow
on:
    schedule:
        # Runs every hour
        - cron: "0 * * * *"
    workflow_dispatch:

jobs:
    update-readme-with-anilist:
        name: Update this repo's README with latest AniList activites
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: AniList readme workflow
              uses: pxseu/anilist-readme@v1.2.1
              with:
                  user_id: zukashishifu
