# src: https://github.com/marketplace/actions/anilist-readme-workflow
name: AniList readme workflow
on:
    schedule:
        # Runs every hour
        - cron: "0 * * * *"
    workflow_dispatch:

jobs:
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
    update-readme-with-anilist:
        name: Update this repo's README with latest AniList activites
        runs-on: ubuntu-latest
       
        steps:
            - uses: actions/checkout@v2
            - name: Favorites anime and currently watching
              uses: lowlighter/metrics@latest
              with:
                  filename: metrics.plugin.anilist.svg
                  token: NOT_NEEDED
                  base: ""
                  plugin_anilist: yes
                  plugin_anilist_medias: anime
                  plugin_anilist_sections: favorites, watching
                  plugin_anilist_limit: 1
                  


